//
// Created by boydj on 2/8/2024.
//

#ifndef BST_VISUALIZER_ASCII_DIGITS_H
#define BST_VISUALIZER_ASCII_DIGITS_H

#define DIGIT_HEIGHT 12;
#define DIGIT_WIDTH 10;


#endif //BST_VISUALIZER_ASCII_DIGITS_H
